### ISSUE TITLE
V1.0 Roadmap

### ISSUE THREAD

**Issue by Rodrigo-Vargas** [Rodrigo-Vargas/waterfall-jekyll-theme#1]
**v0.10.1**

- [x] *Bug* Uncaught ReferenceError: getDefaultThemeOption is not defined
- [x] *Bug* Google Tag Manager code is not working
---

**v0.11**
- [ ] *Enhancement* PWA Support
- [ ] *Enhancement* Improve 404 page
- [ ] *Enhancement* Document does not have a meta description

---

**v0.12**
- [ ] *Development Enhancement* Create a script to automate gem publish
- [ ] *Development Enhancement* Create a good docs structure

**v0.6**

- [x] *Bug* Remove development config from gem publish
- [x] *Bug* Top nav wont work on internal pages
- [x] *Bug* Blog post cards are overlapping top nav
- [x] *Bug* If the content of blog post cards are too big, they are passing the card size

- [x] *Enhancement* Hide Works section if dont have any work
- [x] *Enhancement* Hide Blog section if dont have any blog

---
**v0.7**

- [x] *Enhancement* Create a layout for post
- [x] *Enhancement* Add button see more on home posts
- [x] *Enhancement* Add button see more on home works
- [x] *Enhancement* Google Analytics Track code
- [x] *Enhancement* Create target option on top nav
---

**v0.8**
- [x] *Enhancement* Basic Multilanguage support
- [x] *Enhancement* Projects featured layout
- [x] *Enhancement* Post items limit on home
---

**v0.9**
- [x] *Enhancement* Dark mode support
- [x] *Enhancement* Allow limit posts per page
- [x] *Enhancement* Create a layout for project detail
- [x] *Enhancement* Create a layout for collection index
---

**v0.10**
- [x] *Enhancement* Hide top nav when scroll down
- [x] *Enhancement* Smooth scroll on click links with target
- [x] *Bug* Collection layout dont considering language
- [x] *Enhancement* Header items dont considering language
---
